### ISSUE TITLE
Migrating from MJML app 1.8.1 to 2.0.1

### ISSUE THREAD

**Issue by davelantto** [mjmlio/mjml-app#119]
Hello,

I apologize if this isn't the right place for this question. I downloaded the latest app version (2.0.1) but I can't find a way to open the emails I created with the previous version (1.8.1). Is this possible, or do I just need to copy-paste the code from the old to new version of the app? 

Thank you so much!

**Comment by meriadec** [comment]
Hey @davelantto, yes I confirm actually the only solution is to copy-paste the code from v1 to v2, because the files are not stored in the same format.

If this option is problematic for many users (e.g having 100 templates on v1), I can maybe write a script to automatically migrate all templates, for a future app version.
