### ISSUE TITLE
Custom Component doesn't render in Preview inside App

### ISSUE THREAD

**Issue by robertkent** [mjmlio/mjml-app#124]
Hi Guys,

Not sure if you're aware but I've gone through the custom component tutorial using the boilerplate to create the <mj-column-image-text> component, everything works and displays fine in the index.html that is compiled, but I get no preview on the mjml side of things within the app.

Should the custom component show in the preview window?

![screen shot 2017-05-06 at 13 14 00](https://cloud.githubusercontent.com/assets/1905523/25770374/e87f0eac-325d-11e7-8953-7c26d604336e.png)

**Comment by meriadec** [comment]
Hey @robertkent , thanks for reporting. I will investigate :)

**Comment by meriadec** [comment]
The problem is that MJML use the process working directory  [to locate the configuration file](https://github.com/mjmlio/mjml/blob/master/packages/mjml-core/src/parsers/config.js#L18).

As a workaround, you can launch MJML App from your custom component directory:

![custom-component-2](https://cloud.githubusercontent.com/assets/315259/25975941/a23a05b6-36b1-11e7-9db3-8ea5da94aa5e.png)

**Comment by meriadec** [comment]
This will work from any folder in MJML App, as soon as MJML release new version. Will close issue when it happen.

**Comment by meriadec** [comment]
It happened.

**Comment by zygimantas** [comment]
@meriadec is it broken?

> Zygimantas [11:15 PM]
> Hello. May anyone confirm that MJML App works with custom components and .mjmlconfig file? Components are in /dist, templates are in /src and .mjmlconfig in / is ignored. Thanks. (edited) 
> Zygimantas [11:24 PM]
> even if I open a boilerplate, I see "unregistered components" errors
> Zygimantas [11:33 PM]
> app 2.10.0, mjml v^4.1.2
