### ISSUE TITLE
Feature Request : Version Control

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#155]
This is probably a much bigger/more intensive feature but would it be possible to create a version/revision control function into the app? That way I can see how the email has developed over the various rounds of review/edits/etc and if needed revert. Currently our workflow for this is by duplicating the .mjml file multiple times and appending the date, but would be nice if the system would auto-save or keep maybe the last 5 revisions. Thoughts?

**Comment by meriadec** [comment]
Hey David!

I totally agree on you point that versionning is a big win when talking about collaborative work. This problem is already handed well by git, and I don't think that adding a _local_ git layer _inside_ the app would add value over using more "native" implementation (command line git, [GitHub Desktop](https://desktop.github.com/), etc.) on the project folder.

After that, what do you think about ability to **link a project to [GitHub Gits](https://gist.github.com/)**, and have a "Sync with Gist" button on the editor view. That would be very simple to share templates (e.g: "Import project from Gist URL"), and Gist can also be private.

**Comment by MateuszDabrowski** [comment]
+1 
One click import from github would be great to keep team easily on most actual version of templates.

**Comment by dshastry** [comment]
I didn't even think of using GIT for templates! To me I was thinking of it as a visual design tool and not code at all. Thats awesome; love it. Yes, I like your suggestion @meriadec. Would be great if we can do it.

**Comment by ddeath** [comment]
I think that it would be great feature. I imagine that it could works like this:

* detect git in project folder
* in app shows button to compare version next to each other

So you could choose which commits you want to compare and it would show you two visuals of emails

**Comment by meriadec** [comment]
For now, the app try to be as simple as possible, and handling git diffs & pals. is already well done by existing tools (like git itself, or the myriad of GUI for it).

The https://github.com/mjmlio/mjml-app/issues/219 issue will ease work with git by letting the user save the files when he want.
