### ISSUE TITLE
Bug: Commenting Out Included Files Doesn't Remove Them From Email

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#160]
Tried commenting out an MJML Include block however, the code was not removed in the email even though the block appears to be visually commented out in the editor. Screenshot attached.

![image](https://user-images.githubusercontent.com/4194561/27494904-7ee56602-5815-11e7-81bc-29be83193533.png)

**Comment by meriadec** [comment]
Interesting :D 

It's weird that the XML parser of MJML does'nt get rid of those comments.
But, as this is related to MJML itself, would you mind to create an issue directly to the [mjml repo](https://github.com/mjmlio/mjml)? Better for tracking.

I will close that one, because there is nothing I can do on the app side. As a quick workaround, you can swap some characters, like using `<mj-YOLOinclude>` tag.

**Comment by dshastry** [comment]
Oh ok cool. I'll do that now
