### ISSUE TITLE
Drag to multi select

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#169]
The click to mark/select a template is a fantastic feature! Selecting a large number of templates however, can be frustrating to click to select each time. Can a click+drag to select/deselect be added?

**Comment by meriadec** [comment]
Interesting. However, clic/drag to select can be quite complex to implement (have to look at boxes intersections, handle when we need to scroll if there is large amount of templates, etc.).

Do you know any lib that provide a similar behaviour? If no, what kind of interactions can you imagine instead of a click+drag to select multiple templates? Maybe a <Shift>+Click on the entire template box?

**Comment by dshastry** [comment]
I'm not aware of any libs that provide anything similar but I'll try and find one. As for solving the interaction, I think if it was possible to group emails into folders or tags (as discussed in #102 and #53 ) then we can just export contents of the whole folder. It would be nice if we can group and export either images or html for all children in a folder. What do you think?

**Comment by meriadec** [comment]
As it sounds specific to personal user workflow, I would rather recommend you having a custom script that generate / copy your emails from multiples folders to one. Providing a generic solution in-app can be a maze :)
