### ISSUE TITLE
Win 2.7 

### ISSUE THREAD

**Issue by simonkrabbe** [mjmlio/mjml-app#183]
There is no .exe available on the releases page. Is it a mistake? :)

**Comment by meriadec** [comment]
Not a mistake, but I have no machine running Windows here to create the build.

@janus-reith is it possible for you to build & upload the Windows release?

**Comment by simonkrabbe** [comment]
It would be much appreciated if you can upload the windows release :)

**Comment by meriadec** [comment]
managed to build it inside a VM.
you can find it [on the 2.7 release page](https://github.com/mjmlio/mjml-app/releases/tag/2.7.0).

**Comment by janus-reith** [comment]
Sorry, saw that too late - I can surely continue to provide the Windows builds. I thought you changed the build workflow and dont need them anymore.

**Comment by meriadec** [comment]
@janus-reith : dunno if you saw, but [mjml-app is detected as a threat by some antivirus](https://github.com/mjmlio/mjml-app/issues/186). I highly suspect it is because I've built it inside a virtual machine ([the one given free by Windows for testing IE 😂 ](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)). Can you try building 2.7.0, then overwriting the current Windows binary?
