### ISSUE TITLE
drop img.png on window

### ISSUE THREAD

**Issue by quiqueciria** [mjmlio/mjml-app#19]
HI!
I have tried to drop a image.png on the window of the app for i get the route in my computer and happened this:
![captura de pantalla 2016-04-07 a las 11 41 32](https://cloud.githubusercontent.com/assets/4340378/14347211/29c316bc-fcb6-11e5-9f4e-274683647c88.png)
Then, I don't can come back to my last doc that i was working, the app it's blocked

Thanks!

**Comment by meriadec** [comment]
Hi, thanks for reporting this.

Actually, the app doesn't support image drag&drop, because we have to define before the behaviour of this feature (image have to be uploaded, and we have to insert an `mj-image` at the cursor position, etc.).
It could be interesting to plan this for future releases.

Anyway, for the moment I think we will just disable the native drop to avoid having this strange behaviour. Fortunately, your template is saved everytime, so you may not have lost anything if you start the app again. Keep updated.

**Comment by meriadec** [comment]
[this stackoverflow answer](http://stackoverflow.com/a/31672770/1845964), @GuillaumeBadi what d'you think?

**Comment by meriadec** [comment]
fixed in https://github.com/mjmlio/mjml-app/commit/f069761e54684ee81715a2f18dbff43e680a34b6
thx @GuillaumeBadi
