### ISSUE TITLE
SVG graphics are not displayed

### ISSUE THREAD

**Issue by snHolst** [mjmlio/mjml-app#202]
< mj-image src="data:image/svg+xml;base64,PD94bWw... / >

![bildschirmfoto 2018-01-03 um 16 02 59](https://user-images.githubusercontent.com/11442037/34525584-c1572eb2-f09f-11e7-9b7a-33925dfd5c80.png)

**Comment by snHolst** [comment]
?

**Comment by meriadec** [comment]
Despite your evident unwillingness lack of details (you didn't even bothered to provide a valid `mj-image` tag), I don't see how this problem is related to mjml-app.

Maybe you want to create an issue on the [MJML repo](https://github.com/mjmlio/mjml), providing [**reproducible test case**](https://mjml.io/try-it-live), or go directly to [the MJML slack](https://slacking-inviter.herokuapp.com/).

**Comment by gubarez** [comment]
Hi,

To elaborate on the mater, if we insert base64 string in the src attribute, it adds the absolute path to the project folder, eg. 
`<mj-image src="data:image/png;base64,...." />`
the output is
`<img src="file:///home/user/mjml-report/data:image/png;base64,...."/>`
