### ISSUE TITLE
Is this app mining crypto?

### ISSUE THREAD

**Issue by gbaggaley** [mjmlio/mjml-app#237]
Emsisoft Antivirus threw this message up when launching the app:

`Behavior Blocker detected suspicious behavior "CryptoMalware" of "C:\...\Downloads\mjml-app-win-x64_2.9.0.exe" (SHA1: 05BD7EAAAE2F912CEE7CD43B9F99DFB512F3E713)`

**Comment by meriadec** [comment]
Lol. Dunno if it's either a false positive from your Antivirus software, or if some files has been corrupted on your computer, but I can ensure there is no crypto miner in the app :smile:. In fact, you don't even need to believe me on my words because the app is fully open source, and you can build your own version.

Beside of that, this is hilarious.

**Comment by gbaggaley** [comment]
Welp, I don't think my head is on straight today D:
It's the first time my AV has popped up in 3 years so it worried me, didn't even think about being able to look at the source code.

Sorry for wasting your time :P

**Comment by meriadec** [comment]
no prob ^^
