### ISSUE TITLE
Feature Request: JSON/POT Template Support

### ISSUE THREAD

**Issue by motleydev** [mjmlio/mjml-app#240]
In the agency where I work we do a lot of multi-lingual versions of e-mails. It would be really nice to have some kind of POT file or basic JSON template support to separate the concerns of content source and layout source. There's a huge ecosystem around PO/POT and it could be a natural integration. https://www.icanlocalize.com/site/tutorials/how-to-translate-with-gettext-po-and-pot-files/

**Comment by iRyusa** [comment]
Hi @motleydev 

Well, this one is a bit tricky because there's a lot of tool to handle that kind of things and implementing each of them would be a bit tricky to maintain. What you should use is some kind of templating system that replace everything you need. 

It won't be implemented because it's not really the purpose of MJML-APP to integrate every tool that email developer could use based on personal taste or even if widely adopted by the community.

As the editor is open source, feel-free to have your own customized fork adapted to your workflow
