### ISSUE TITLE
-bash: mjml: command not found

### ISSUE THREAD

**Issue by jeanjacquesrepository** [mjmlio/mjml-app#243]
Hi,
I'm following the install steps outlined here: [https://mjml.io/download](https://mjml.io/download)

After tying npm init -y && npm install mjml

I get these error messages

npm ERR! path /Volumes/GoogleDrive/Mon Drive/perso/coding/Python/repositories/email-kits/node_modules/chokidar/node_modules/randomatic/node_modules/kind-of/package.json.4174865573
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/Volumes/GoogleDrive/Mon Drive/perso/coding/Python/repositories/email-kits/node_modules/chokidar/node_modules/randomatic/node_modules/kind-of/package.json.4174865573'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michel/.npm/_logs/2018-05-04T13_40_21_545Z-debug.log

Please find attached content from 2018-05-04T13_40_21_545Z-debug.log
[2018-05-04T13_40_21_545Z-debug.log](https://github.com/mjmlio/mjml-app/files/1974642/2018-05-04T13_40_21_545Z-debug.log)

When I try to type mjml within the terminal all I get is this error message -bash: mjml: command not found

Thanks for your support

**Comment by iRyusa** [comment]
Hi @jeanjacquesrepository 

If you're not so familiar with node & cmd line I suggest you to use something like mjml-app, it's an editor with pre installed mjml so it require almost 0 setup.

For your issue, looks like you're in a weird folder, i don't know it's really hard to help you without any idea if you're in an empty folder or a project with already node dependencies.

Looks like you're using a really old version of node/npm because it no longer nest node_modules like that.

This repository is about mjml-app, so i'm closing the issue because it's not related to the app, here's the main repo of MJML https://github.com/mjmlio/mjml
