### ISSUE TITLE
Feature Request: Support Preview Extensions/Middleware

### ISSUE THREAD

**Issue by dannief** [mjmlio/mjml-app#249]
I use mjml with handlebars templates, I imagine most people use some kind of templating system for non-trivial emails. I read this issue #240, and I agree it shouldn't be the responsibility of the mjml-app to support all the various ways placeholders can be populated in an email template. But how about supporting the use of extensions? 

We would just need a hook to be able process the mjml file before it is converted to HTML. I think at minimum we can specify the extensions that will be hooked into the pipeline in preferences, then from there, each extension can specify its own configuration. For example, I would specify in a config file that for a particular email template, I want the handlebars extension to process the mjml file with a particular context (the data that should replace the placeholders) every time preview is triggered or the email is sent. 

It would be really helpful to see exactly how an email will be displayed, without having to implement the email in the consuming application.

I also imagine that more advanced scenarios could be supported also, if there is a demand, like allowing extensions to create custom UIs.

What do you think? Do you think at minimum preview extensions can be supported?

**Comment by iRyusa** [comment]
Hi @dannief 

Well, on the paper : yes it would be awesome. But ... it's  really time consuming to develop a fully extendable editor as VSCode or Atom could be nowadays and I don't think we have the time to implement such thing. 

Here's the limit of MJML-App, a small convenient editor with really "just-enough" feature to get you produce MJML Emails without knowing the cmd line.

And I think for this case it would be really faster to setup properly a gulp task that watch & compile for you rather than expose an API to customize the build process of a save.

I think as of #240 we can close the issue, because the effort required for this kind of task is really big (API+Doc, Extension Market Place, Download Manager, ... ) and it's really unrealistic regarding the team behind MJML to work on it for now

**Comment by dannief** [comment]
I understand where you are coming from, but to be clear, I really wasn't thinking Market Place, Download Managers or any of that. I was just thinking that the team could provide a hook and other developers would take over. Users would install the extension from npm or download a zip file, follow the extension author's instructions about configuration and then from mjml app's side, modify config so the app knows to load the extension. 

If this is completely out of scope, I understand. Will figure something out for my purposes as you suggested.

**Comment by ngarnier** [comment]
This is specifically the very hard part:
> provide a hook and other developers would take over
> modify config so the app knows to load the extension

This means being able to create something generic enough on MJML App's side when extensions can be very different (especially as we don't even know what they would be yet, and if there's an actual need for something generic).

I think the most realistic, if you're interested, is to start by forking the app and work on a handlebars integration on your side to match your need. If we notice others do the same for other extensions, then it might be worth considering a pluggable extension system. For now, we haven't seen a need big enough to justify the cost of developing something that complex.
