### ISSUE TITLE
App does not quit

### ISSUE THREAD

**Issue by ParallelUniv3rse** [mjmlio/mjml-app#267]
**Describe the bug**
The application does not terminate upon closing it. Trying to open it again results in a "This application is not open anymore" error. It needs to be force quit every time from the top left apple icon menu.

**To Reproduce**
1. Open the application
2. Try to quit - doesn't work
3. Close the application's window
4. The app still seems to be running in the dock, but clicking does nothing
5. Launch from spotlight produces the mentioned error.

**Expected behavior**
The application quits normally.

**Video recording**
http://files.wild.as/5Pirue

**Environment (please complete the following information):**
 - OS: MacOS High sierra & Mojave, experienced the error on both.
 - App Version 2.10.0

I tried to lookup the version number while in the "Closed but still running" state and the about window showed this up. I figured it might help. 

A JavaScript error occurred in the main process
`Uncaught Exception:
Error: Object has been destroyed
    at mainWindow (/Applications/MJML.app/Contents/Resources/app.asar/webpack:/src/menu.js:26:13)
    at MenuItem.click (/Applications/MJML.app/Contents/Resources/electron.asar/browser/api/menu-item.js:52:9)
    at Function.executeCommand (/Applications/MJML.app/Contents/Resources/electron.asar/browser/api/menu.js:34:15)`

**Comment by meriadec** [comment]
relatable: https://github.com/mjmlio/mjml-app/blob/master/src/main/index.js#L90

**Comment by kmcb777** [comment]
@meriadec so should we just remove this check and close the app anyway ?
It's indeed a bit annoying that the mjml app icon stays in the doc

**Comment by punqbund** [comment]
Furthermore you cannot quit the app by right-clicking the dock icon and selecting 'quit', it just ignores the command. 
Annoying is also that in the windowless state the mjml app is preventing the shutdown of the Mac. In order to complete the shutdown procedure you need to click the dock icon to focus the app and then manually quit it via the top menu or by `⌘+Q`.

**Comment by punqbund** [comment]
Furthermore you cannot quit the app by right-clicking the dock icon and selecting 'quit', it just ignores the command. 
Annoying is also that the running mjml app is preventing the shutdown of the Mac. In order to complete the shutdown procedure you need to focus the app and then manually quit it via the top menu or by `⌘+Q`.

**Comment by meriadec** [comment]
@kmcb777 yep go ahead :+1: i always have found this osx behaviour stupid
