### ISSUE TITLE
Allow renaming of MJML file

### ISSUE THREAD

**Issue by n1ckc1n** [mjmlio/mjml-app#270]
Is there any way to rename the mjml files without losing the preview in the app home screen? It seems to only show the preview if the mjml file is named index.

![image](https://user-images.githubusercontent.com/23665075/47744634-c4f94e00-dc4f-11e8-8db4-3ae9d514d1b8.png)

**Comment by n1ckc1n** [comment]
I'm on the latest version and it doesn't work for me.

**Steps to reproduce:**
1. Create a new project
2. Close MJML App
3. Browse to project folder on computer
4. Rename index.mjml to something else
5. Double click to open the newly named file
6. Click back to go to menu screen
7. Thumbnail is now the generic envelope image

**Comment by MateuszDabrowski** [comment]
It might be a stupid question, but I saw many people doing this mistake - are you adding .mjml on the end of the new name? Without it app won't recognize the file and the outcome will be exactly like the one you show.

**Comment by n1ckc1n** [comment]
Thank you for your reply. 

Yes, I'm on Windows 10 so extensions aren't included in the file names. Just to test I added the .mjml but still no thumbnail.

**Comment by kmcb777** [comment]
@n1ckc1n I made a PR so that if there is no index.mjml in the project, it will look for any other mjml file in the project folder, and will use it for Preview. It should be ok for most use case.
Allowing to specify exactly which file you want to use as Preview would require some extra work on the menu, i'm not sure it's worth it
