### ISSUE TITLE
unitless Line-heights not supported - but is in MJML itself

### ISSUE THREAD

**Issue by TheWebTech** [mjmlio/mjml-app#280]
Is your feature request related to a problem? Please describe.
The line-height property supports using it unitless, and this is most often the most reliable way of using it. As far as I'm aware there are no issues with using unitless in any email clients.

https://www.campaignmonitor.com/css/text-fonts/line-height/

Describe the solution you'd like
allow unitless line-height attribute in mjml markup

https://github.com/mjmlio/mjml/issues/1536

Guessing problem is an outdated version of MJML being used in the app

**Comment by kmcb777** [comment]
@TheWebTech Hi again, just for information, note that this kind of validation warnings are just here to warn about unsupported attributes, they won't prevent the rendering.
Concerning your issue the only problem was that the allowed unit types weren't properly defined for line-heights, so for now you can ignore this warning and safely use unitless line-height anyway.
And this will be fixed in the next app release 👍
