### ISSUE TITLE
Request give dark mode on mjml app

### ISSUE THREAD

**Issue by prashantdwivedi** [mjmlio/mjml-app#333]
**Feature request**
On current https://mjmlio.github.io/mjml-app/ 
Feature section mjml app editor section in `dark mode`. 
why that dark version is not in the current version or I miss something?

![resize](https://user-images.githubusercontent.com/6306052/98591063-bab9c200-22f5-11eb-9b7c-19efebf17c47.gif)

**Comment by Sambuxc** [comment]
This would be pretty cool, but possibly not capable of actually previewing how it would truly look on email clients. This is because there are lots of differents between the email clients.

Today I tested on the Apple Mail app with dark mode and it doesn't change anything, however, Outlook does and it even gets rid of section's background-colors I set as white.
Does anyone know how to keep white background-colors for dark mode?
