### ISSUE TITLE
Custom component

### ISSUE THREAD

**Issue by maxs15** [mjmlio/mjml-app#35]
Hey guys,

Love your app !
I was wondering, is there any way to use custom components ?

**Comment by GuillaumeBadi** [comment]
Hey!

That's an interesting question. MJML2 allows us to import components with a `.mjmlconfig` file. Let me have a look at that today and come back to you.

**Comment by meriadec** [comment]
Hi Maxime, this is not possible at this time, but we definitely have to consider it if many people need it.
It could be a very interesting feature in future release.

The road map for it will be:

  - define the UX for custom components gestion (additional menu in home? how to "attach" a custom component to a template? etc.)
  - define the UX for custom component edition (dedicated preview? how to debug it, because a custom component is js code?)
  - the custom component code have to be compiled with babel + jsx, and the node require cache have to be invalidated for each time we modify the component. Also, we should have an easier way to load them than using `.mjmconfig`. This is the blocking point and we may do a very little POC before doing anything else.

Let's let the issue open, to reming us it everyday 😄

**Comment by GuillaumeBadi** [comment]
It would be cool if the mjml engine looked for an `.mjmlconfig` in the home directory too

**Comment by meriadec** [comment]
IMHO, it would be a better idea to store the "children" components of a template [_inside_ the template](https://github.com/mjmlio/mjml-app/blob/d30792cb8132d2a3603f5ce98ad69042ce9a39c6/src/actions/templates.js#L179-L186). Because we don't need to load all possible components for generate a template if the template use only one.

**Comment by maxs15** [comment]
Awesome !
I agree with you @meriadec, in my opinion I would see:
- A new tab "My components" where you can include components from different directories
- The possibility to edit a component with an editor and a preview like the template editing + the JS console for debug purposes.
- Add a new import section in the template editor to use a custom component

I'm looking forward for such a feature, email development would become so much faster by allowing developers to create components.
We could even think about allowing component's import directly from Github/npm, using the community components would be easy as hell ! 🔥 🔥 🔥

**Comment by PatriotRDX** [comment]
Any updates on this? Adding custom components would make it easier for me to get my non-dev team members making their own emails without having to show them how to use Gulp.

**Comment by meriadec** [comment]
Hey @PatriotRDX , to be honest this is not likely to come in the actual mjml-app version (the way templates are stored don't help..), maybe it can be added to the [MJML App v2](https://github.com/mjmlio/mjml-app/tree/2.0.0) roadmap.

Problem with that feature is that it force MJML App to include its own babel parser, etc to be able to compile custom components written like in the docs, and maybe going against he app focus on simplicity.

Note that MJML App v2 will support [mj-include](https://mjml.io/documentation/#mj-include) out of the box, maybe it can fit your needs?

**Comment by PatriotRDX** [comment]
@meriadec I have a few custom components I forked and modified from another user here that add the tags <mc-section> and <mc-image>. These append custom MailChimp attributes into the right place to make the templates editable in design mode on MailChimp's website. I run these through the Gulp process included in the MJML Boilerplate project. I don't think importing a .mjml file will help much because it relies on Javascript to parse and correctly assign the MailChimp attributes.

I'll look for the v2 version in the future. Thanks for the update by the way.

**Comment by meriadec** [comment]
hey @PatriotRDX 

this is possible now in v2, but with the obligation to launch the app *from the custom component directory* as described here: https://github.com/mjmlio/mjml-app/issues/124

I close this issue in favor of the above. Keep updated!
