### ISSUE TITLE
Exclude <br> Tag from autocomplete

### ISSUE THREAD

**Issue by janus-reith** [mjmlio/mjml-app#51]
Using `<br>` will result in `<br></br>` and therefore two new lines.

**Comment by meriadec** [comment]
Hey Janus,
after a few tries, I didn't achieve to tweak [ace xml mode](https://github.com/thlorenz/brace/blob/master/mode/xml.js) to avoid your problem.
As a quick workaround, you can type `<br />` instead of `<br>`, which will not be closed with another tag.

![cutted](https://cloud.githubusercontent.com/assets/315259/16178087/807b34fe-363f-11e6-8a9c-3d93976f4fed.gif)

**Comment by janus-reith** [comment]
Thanks for the link,
I will also have a look as soon as I find the time.

**Comment by meriadec** [comment]
Closing this one for the moment, because no development is planned. Feel free to reopen if u find a fix :)
