### ISSUE TITLE
Set encoding per template

### ISSUE THREAD

**Issue by robsonsobral** [mjmlio/mjml-app#55]
Ok, this is a hard one.

Is it possible to set the encoding of each template? Some of my clients use email tools which doesn't use UTF-8. So, some emails need to be send and UFT-8 and others don't.

Thank you!

related: https://github.com/mjmlio/mjml/issues/315

**Comment by meriadec** [comment]
Hi, it would be a bit problematic to implement it currently, because we load all templates at app startup, and we read them as utf-8 (https://github.com/mjmlio/mjml-app/blob/master/src/helpers/file-system.js#L47). Allowing to set encoding per template would be a pretty big refactor, including tests, etc, and I currently have no time to work on such feature 😢 

I can advise you to use some custom toolchain, it will more fit your needs, e.g https://github.com/heldinz/gulp-convert-encoding
