### ISSUE TITLE
Image border-radius tag not working

### ISSUE THREAD

**Issue by jeffreywyman** [mjmlio/mjml-app#59]
Using this tag in the mj-image component will not render a border radius:

border-radius="24px"

**Comment by meriadec** [comment]
Hi, I just re-uploaded the releases for osx. Check them in the [release page](https://github.com/mjmlio/mjml-app/releases/tag/1.4.0). Problem seems be fixed by upgrading mjml.

![screen shot 2016-08-17 at 17 02 26](https://cloud.githubusercontent.com/assets/315259/17742568/c77f2b78-64a0-11e6-9d08-e01883716fe2.png)

Feel free to re-open if the pb persist.
