### ISSUE TITLE
Request: Email Variables

### ISSUE THREAD

**Issue by dshastry** [mjmlio/mjml-app#98]
I have a universal header/footer for the email designs that our team puts together. I am pulling these in via an include. I know I can copy over the mjml code to the web interface to add in the variables, but it would be nice if we could define a list of variables such as say email name or unsubscribe link url in the desktop version too. This way we won't have to duplicate the whole project and hand modify the header/footer each time to display this information. 

Screenshot of feature request below:

![image](https://cloud.githubusercontent.com/assets/4194561/25092655/48859c4e-2354-11e7-90d0-bae76e68e91b.png)

![image](https://cloud.githubusercontent.com/assets/4194561/25092720/8d8cd780-2354-11e7-9237-13f9ca9cb199.png)

**Comment by dshastry** [comment]
Being able to customize/define any piece of data as a variable would be an awesome feature!

**Comment by meriadec** [comment]
Hey @dshastry , I'm mitigated for that one. I prefer to keep the app agnostic from any templating language (here you show Mailjet vars/tags, but it can also be Handlebars vars, or whatever).

Keep in mind that you can always use [mj-raw](https://mjml.io/documentation/#mjml-raw) to put whatever you want in your template, and that will be rendered the same in the final HTML: handly for variables, etc.

If the feature is massively requested, we could re-open issue in the future.

**Comment by dshastry** [comment]
Ok that makes sense. I am all for keeping it agnostic too. It would be nice if you could define the custom fields/variables in the email settings and then reference those in the email. It just makes it easier to reference the variable vs hand changing all the fields. I'll play around with MJ-Raw for now though. Thanks @meriadec 😄

**Comment by philspbr** [comment]
Is there any news on this?
It would be great if we were able to define a variable (i.e. a google analytics tracking parameter ?utm_source=example1&utm_campaign=example2) which then could be added to each link in the template like this
<a href=¨https://www.example.com/link<mj-variable>">Link</a>

**Comment by meriadec** [comment]
@philspbr you can always put some variable in your templates, then process them with, for example mustache (documentation: https://mustache.github.io/mustache.5.html). There is implementation for almost every language.

**Comment by ChrisPlaneta** [comment]
Hi. I just wanted to add my +1 to have variables implemented by default. I'm using your windows app and I'm not familiar with any templating engine so an off-the-box variables feature would be what I would welcome with open hands.

Cheers!

**Comment by insetavijit** [comment]
i think we can use pug .
we can use pug -> mjml . 
yes with gulp #4 
pluse we can use browserSynce too in this way .
what do you think guys ?

i will be creating a seed project to implement what i am saying and after i create it i will post the link in comments . say cheeejjjjjjj

**Comment by WadeShuler** [comment]
Stumbled upon this page because I was looking for exactly the same thing.

I think MJML should support some basic variable use.

Use Case:

I am working on a large email project with multiple pages. They all use the same layout, but it's complex. I used Atom to create folders in my project dir as it seems MJML can not create them, but it navigates (views) them just fine? So I created a `templates` folder, then within that multiple folders named the corresponding section (footer, header, body). The `header` child template directory has a few mjml files (logo.mjml and navbar.mjml).

So I am a few levels deep. The call to my logo image is a `/templates/header/logo.mjml` and looks like this, just so MJML preview can render it `"../../../assets/images/logo.png"`.

Keep in mind, in development, the final URL is usually not known, and that path surely isn't going to work.

---

Maybe in the root of the project have a config file where we house our variables. Then I could use an image URL like so: `{MJML-ROOT-PATH}/assets/images/logo.png`

This `{MJML-ROOT-PATH}` could be my localhost during development, then the client's test domain or mine for a preview, then the client's real domain or Amazon S3 for the final email that gets sent to their subscribers.

While all 3 scenarios (dev, test, live) would show the same image, the URL's are all different. This is important for exporting the HTML. 

Ensure the variables can handle including other tags to support Handlebars and other templating engines.

I would rather swap the URL once in a config file, then export the project's HTML, than have to find/replace 200 instances over 30 files.

Then if your using a templating engine, like handlebars, you could still be happy by passing your tag instead, and get `{{HANDLEBAR-TAG}}/assets/images/logo.png` in the final rendered HTML.

Even better if the config file can support multiple environment modes. One would have to be used by default in MJML all the time, or allow toggling between them so you could spot errors. For example, different variables for dev, test, and live. Then export as "test" so the files are ready for my test environment (client preview) or export as "live" for code ready to be inserted into the mailing system and mailed out. 

I don't feel like this makes MJML any less agnostic, more like making it play better with others. MJML is leaving us with a major gap between the development/creation and the live production stages. The result is, I have to manually find/replace tons of spots.
